import { motion } from "framer-motion";
import { useLocation } from "wouter";

export default function Terms() {
  const [, setLocation] = useLocation();

  return (
    <div className="legal-page">
      <header className="legal-header">
        <nav className="nav">
          <motion.div
            className="logo"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6 }}
            onClick={() => setLocation("/")}
            style={{ cursor: "pointer" }}
          >
            <span className="logo-icon">🍳</span>
            <span className="logo-text">Cook Is Easy</span>
          </motion.div>
          <motion.button
            className="nav-cta"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            onClick={() => setLocation("/app")}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
          >
            Start Cooking
          </motion.button>
        </nav>
      </header>

      <main className="legal-content">
        <motion.div
          className="content-wrapper"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <h1>Terms of Service</h1>
          <p className="last-updated">Last updated: February 2, 2026</p>

          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using Cook Is Easy ("the Service"), you agree to be bound by these
              Terms of Service. If you do not agree to these terms, please do not use our Service.
            </p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>
              Cook Is Easy is a recipe discovery platform that helps users find recipes based on
              available ingredients. Our Service includes:
            </p>
            <ul>
              <li>Ingredient-based recipe search</li>
              <li>AI-powered recipe generation</li>
              <li>Ingredient substitution suggestions</li>
              <li>Personal preference storage</li>
            </ul>
          </section>

          <section>
            <h2>3. User Accounts</h2>
            <p>
              To access certain features, you must create an account. You agree to:
            </p>
            <ul>
              <li>Provide accurate and complete information</li>
              <li>Maintain the security of your password</li>
              <li>Accept responsibility for all activities under your account</li>
              <li>Notify us immediately of any unauthorized access</li>
            </ul>
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2>4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the Service for any illegal purpose</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with the proper functioning of the Service</li>
              <li>Scrape, copy, or redistribute our content without permission</li>
              <li>Use automated systems to access the Service excessively</li>
              <li>Impersonate others or provide false information</li>
            </ul>
          </section>

          <section>
            <h2>5. Recipe Content</h2>

            <h3>Database Recipes</h3>
            <p>
              Our recipe database includes curated recipes from various sources. While we strive
              for accuracy, we do not guarantee that all recipes will produce the expected results.
            </p>

            <h3>AI-Generated Recipes</h3>
            <p>
              Recipes generated by our AI are provided "as-is." While we use advanced models to
              ensure quality, AI-generated content may occasionally contain errors or unusual
              ingredient combinations. Please use your judgment when following AI-generated recipes.
            </p>

            <h3>Dietary and Allergy Information</h3>
            <p>
              <strong>Important:</strong> While we provide dietary tags and allergen information,
              this information may not be complete or accurate. If you have food allergies or
              dietary restrictions, always verify ingredients independently. Cook Is Easy is not
              responsible for allergic reactions or dietary complications.
            </p>
          </section>

          <section>
            <h2>6. Intellectual Property</h2>
            <p>
              The Service, including its design, features, and content, is owned by Cook Is Easy
              and protected by intellectual property laws. You may not:
            </p>
            <ul>
              <li>Copy or modify the Service or its content</li>
              <li>Use our branding without permission</li>
              <li>Create derivative works based on our Service</li>
            </ul>
            <p>
              Recipes themselves are generally not copyrightable, but our unique presentation,
              matching algorithms, and generated content are proprietary.
            </p>
          </section>

          <section>
            <h2>7. Free Service</h2>
            <p>
              Cook Is Easy is currently provided free of charge. We reserve the right to:
            </p>
            <ul>
              <li>Introduce premium features in the future</li>
              <li>Modify or discontinue features</li>
              <li>Implement usage limits</li>
            </ul>
            <p>
              Core functionality (basic recipe search) will remain free.
            </p>
          </section>

          <section>
            <h2>8. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND,
              EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT:
            </p>
            <ul>
              <li>The Service will be uninterrupted or error-free</li>
              <li>Recipes will produce the desired results</li>
              <li>Information provided is complete or accurate</li>
              <li>The Service will meet your specific requirements</li>
            </ul>
          </section>

          <section>
            <h2>9. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, COOK IS EASY SHALL NOT BE LIABLE FOR ANY
              INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM
              YOUR USE OF THE SERVICE.
            </p>
            <p>
              This includes, but is not limited to, damages from:
            </p>
            <ul>
              <li>Food-related illness or allergic reactions</li>
              <li>Kitchen accidents</li>
              <li>Loss of data</li>
              <li>Service interruptions</li>
            </ul>
          </section>

          <section>
            <h2>10. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Cook Is Easy, its officers, directors,
              employees, and agents from any claims, damages, or expenses arising from your
              use of the Service or violation of these terms.
            </p>
          </section>

          <section>
            <h2>11. Changes to Terms</h2>
            <p>
              We may modify these terms at any time. Continued use of the Service after changes
              constitutes acceptance of the new terms. We will notify users of significant changes
              via email or in-app notification.
            </p>
          </section>

          <section>
            <h2>12. Termination</h2>
            <p>
              You may stop using the Service at any time. We may terminate or suspend your access
              immediately, without prior notice, for conduct that violates these terms or is
              harmful to other users or the Service.
            </p>
          </section>

          <section>
            <h2>13. Governing Law</h2>
            <p>
              These terms shall be governed by and construed in accordance with applicable laws,
              without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2>14. Contact</h2>
            <p>
              For questions about these Terms of Service, please contact us at:
            </p>
            <p>
              <strong>Email:</strong> legal@cookiseasy.app
            </p>
          </section>
        </motion.div>
      </main>

      <footer className="legal-footer">
        <div className="footer-content">
          <div className="footer-links">
            <a onClick={() => setLocation("/about")}>About</a>
            <a onClick={() => setLocation("/privacy")}>Privacy</a>
            <a onClick={() => setLocation("/terms")}>Terms</a>
            <a onClick={() => setLocation("/contact")}>Contact</a>
          </div>
          <p className="footer-copyright">© 2024 Cook Is Easy. Made with 🧡 for home cooks everywhere.</p>
        </div>
      </footer>

      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;0,9..144,700;1,9..144,400&family=DM+Sans:wght@400;500;600&display=swap');

        .legal-page {
          --color-cream: #FDF8F3;
          --color-terracotta: #C84B31;
          --color-terracotta-dark: #A63D28;
          --color-sage: #7D9D6D;
          --color-charcoal: #2D3436;
          --color-warm-gray: #636E72;
          --font-display: 'Fraunces', Georgia, serif;
          --font-body: 'DM Sans', -apple-system, sans-serif;

          min-height: 100vh;
          background: var(--color-cream);
          color: var(--color-charcoal);
          font-family: var(--font-body);
          display: flex;
          flex-direction: column;
        }

        .legal-header {
          background: var(--color-cream);
          border-bottom: 1px solid rgba(0,0,0,0.05);
        }

        .nav {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 1.5rem 4rem;
          max-width: 1200px;
          margin: 0 auto;
        }

        .logo {
          display: flex;
          align-items: center;
          gap: 0.75rem;
        }

        .logo-icon { font-size: 2rem; }

        .logo-text {
          font-family: var(--font-display);
          font-size: 1.5rem;
          font-weight: 600;
          color: var(--color-charcoal);
        }

        .nav-cta {
          background: var(--color-terracotta);
          color: white;
          border: none;
          padding: 0.875rem 1.75rem;
          border-radius: 100px;
          font-family: var(--font-body);
          font-weight: 600;
          font-size: 0.95rem;
          cursor: pointer;
          transition: background 0.3s ease;
        }

        .nav-cta:hover { background: var(--color-terracotta-dark); }

        .legal-content {
          flex: 1;
          padding: 4rem 2rem;
        }

        .content-wrapper {
          max-width: 800px;
          margin: 0 auto;
        }

        h1 {
          font-family: var(--font-display);
          font-size: 3rem;
          font-weight: 700;
          margin-bottom: 0.5rem;
          color: var(--color-charcoal);
        }

        .last-updated {
          font-size: 0.95rem;
          color: var(--color-warm-gray);
          margin-bottom: 3rem;
        }

        h2 {
          font-family: var(--font-display);
          font-size: 1.5rem;
          font-weight: 600;
          margin-top: 3rem;
          margin-bottom: 1rem;
          color: var(--color-charcoal);
        }

        h3 {
          font-family: var(--font-body);
          font-size: 1.1rem;
          font-weight: 600;
          margin-top: 1.5rem;
          margin-bottom: 0.5rem;
          color: var(--color-charcoal);
        }

        p {
          font-size: 1rem;
          line-height: 1.8;
          color: var(--color-warm-gray);
          margin-bottom: 1rem;
        }

        ul {
          margin: 0.5rem 0 1rem 1.5rem;
          color: var(--color-warm-gray);
        }

        li {
          font-size: 1rem;
          line-height: 1.8;
          margin-bottom: 0.5rem;
        }

        li strong {
          color: var(--color-charcoal);
        }

        .legal-footer {
          background: var(--color-charcoal);
          padding: 2rem;
        }

        .footer-content {
          max-width: 1200px;
          margin: 0 auto;
          text-align: center;
        }

        .footer-links {
          display: flex;
          justify-content: center;
          gap: 2rem;
          margin-bottom: 1rem;
        }

        .footer-links a {
          color: rgba(255,255,255,0.7);
          text-decoration: none;
          cursor: pointer;
          transition: color 0.2s;
        }

        .footer-links a:hover { color: white; }

        .footer-copyright {
          font-size: 0.85rem;
          color: rgba(255,255,255,0.4);
        }

        @media (max-width: 768px) {
          .nav { padding: 1.25rem 1.5rem; }
          h1 { font-size: 2rem; }
        }
      `}</style>
    </div>
  );
}
